version: '3.9' 

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=Cultura_bd_new1;User Id=AdminLogin;Password=Your_password123!;"
      "ConnectionStrings": {
  "DefaultConnection": "Server=db;Database=Cultura_bd_new1;User Id=AdminLogin;Password=12345;"
}

    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=12345"
      - "ACCEPT_EULA=Y"
    container_name: mssql
   
