version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString="Server=db;Database=Cultura_bd_new1;User Id=AdminLogin;Password=Your_password123!;"
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123!"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    ports:
      - "1433:1433"

  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
    ports:
      - '8080:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./gitlab-config:/etc/gitlab
      - ./gitlab-data:/var/opt/gitlab
      - ./gitlab-logs:/var/log/gitlab

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: always
    environment:
      MM_SERVICESETTINGS_SITEURL: 'http://mattermost.example.com'
    ports:
      - '8065:8065'
    volumes:
      - ./mattermost-data:/mattermost/data

  osu-web:
    image: ghcr.io/ppy/osu-web:latest
    restart: always
    environment:
      APP_URL: 'http://osu.example.com'
    ports:
      - '8000:8000'
    volumes:
      - ./osu-data:/osu-web/data
